# Generated by Django 3.1.6 on 2021-02-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rawg_id', models.IntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('age_rating_id', models.IntegerField()),
                ('sys_req', models.TextField()),
            ],
            options={
                'db_table': 'entitys.games',
                'managed': False,
            },
        ),
    ]
