# Generated by Django 3.1.6 on 2021-02-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210218_0023'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='games',
            table='games',
        ),
    ]
