# Generated by Django 3.1.6 on 2021-02-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210218_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Games', 'verbose_name_plural': 'Games'},
        ),
    ]
