# Generated by Django 3.1.6 on 2021-02-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210218_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'managed': False, 'verbose_name': 'Games', 'verbose_name_plural': 'Games'},
        ),
    ]
